
import React, { ReactNode } from 'react';
import { Deck } from './types';

export const CARD_WIDTH = 250;
export const CARD_HEIGHT = 350;

// Avatar: The Last Airbender Sets
export const ATLA_SETS = [
    { code: 'tla', name: 'Avatar: The Last Airbender', quote: 'Water. Earth. Fire. Air.' },
    { code: 'tle', name: 'Avatar: The Last Airbender Eternal', quote: 'Some friendships are so strong, they can even transcend lifetimes.' },
    { code: 'ptla', name: 'Avatar: The Last Airbender Promos', quote: 'My cabbages!' },
    { code: 'ttla', name: 'Avatar: The Last Airbender Tokens', quote: 'Everything changed when the Fire Nation attacked.' },
    { code: 'atla', name: 'Avatar: The Last Airbender Art Series', quote: 'It\'s a giant mushroom! Maybe it\'s friendly!' },
    { code: 'ttle', name: 'Avatar: The Last Airbender Eternal Tokens', quote: 'Drink cactus juice. It\'ll quench ya.' },
    { code: 'atle', name: 'Avatar: The Last Airbender Eternal Art Series', quote: 'That\'s rough, buddy.' },
    { code: 'ftla', name: 'Avatar: The Last Airbender Beginner Box Front Cards', quote: 'You must look within yourself to save yourself from your other self.' },
    { code: 'jtla', name: 'Avatar: The Last Airbender Jumpstart Front Cards', quote: 'Flameo, hotman!' }
];

// Final Fantasy Sets
export const FF_SETS = [
    { code: 'fin', name: 'Final Fantasy', quote: 'Listen to my story. This may be our last chance.' },
    { code: 'fca', name: 'Final Fantasy: Through the Ages', quote: 'Whatever happens, we’ll be there to protect you.' },
    { code: 'pfin', name: 'Final Fantasy Promos', quote: 'Not interested.' },
    { code: 'tfin', name: 'Final Fantasy Tokens', quote: 'Kweh!' },
    { code: 'rfin', name: 'Final Fantasy Regional Promos', quote: 'This is my story.' },
    { code: 'fic', name: 'Final Fantasy Commander', quote: 'I, Garland, will knock you all down!' },
    { code: 'tfic', name: 'Final Fantasy Commander Tokens', quote: 'Kupo!' },
    { code: 'afin', name: 'Final Fantasy Art Series', quote: 'Such devastation! This was not my intention!' },
    { code: 'pss5', name: 'FIN Standard Showdown', quote: 'Let\'s mosey.' },
    { code: 'wfin', name: 'FIN Asia WPN Promo Tokens', quote: 'Victory fanfares playing in the distance.' }
];

// Lorwyn Eclipsed Sets
export const ECL_SETS = [
    { code: 'ecl', name: 'Lorwyn Eclipsed', quote: 'Day and night are but two sides of the same coin.' },
    { code: 'tecl', name: 'Lorwyn Eclipsed Tokens', quote: 'Shadows lengthen.' },
    { code: 'ecc', name: 'Lorwyn Eclipsed Commander', quote: 'Legends born from twilight.' },
    { code: 'tecc', name: 'Lorwyn Eclipsed Commander Tokens', quote: 'Spirits of the eclipse.' }
];

export const UNIVERSES = {
  atla: {
    name: "Avatar: The Last Airbender",
    sets: ATLA_SETS,
    hasJumpstart: true,
    themeColor: 'text-black',
    logo: '/images/TLA.png',
    iconType: 'svg',
    viewBox: '0 0 140 185',
    icon: 'M125.795 22.897c8.394 10.64 13.41 24.066 13.41 38.662 0 2.247.072 8.658.104 12.582.058 6.684-.026 12.627-.512 23.747 0 0 5.82-7.333 7.72-8.71 3.046-2.202 5.885-.695 6.695 1.338 1.789 4.501.052 24.54-.512 24.573-1.854 8.964-17.688 17.148-20.644 17.187-3.707 18.96-34.565 50.178-55.066 50.718V183c-20.5-.559-51.34-31.77-55.046-50.717-2.956-.046-18.79-8.224-20.644-17.188-.564-.032-2.3-20.071-.512-24.573.81-2.04 3.65-3.54 6.696-1.338 1.905 1.37 7.719 8.71 7.719 8.71-.48-11.126-.57-17.07-.506-23.747.033-3.923.104-10.334.104-12.582 0-14.595 5.017-28.028 13.417-38.668 7.777-9.854 18.459-17.31 30.734-21.078a48.025 48.025 0 0 1 1.887-.546L66.626.006 62.478 61.65l-23.63-.085 38.142 42.936 38.15-42.942-23.631.084L87.36 0l5.794 1.267c.635.175 1.264.357 1.886.545 12.282 3.768 22.964 11.225 30.741 21.085h.013Zm-81.657 77.465c-5.387-1.157-9.177.563-11.56 3.69-1.983 2.61-4.83 2.834-5.433 5.86-1.315 6.62 6.468 13.905 16.385 16.041 9.917 2.136 19.048 1.305 20.364-5.322 1.315-6.62-9.839-18.139-19.756-20.275v.006Zm65.718-.004c-9.918 2.137-21.065 13.65-19.75 20.276 1.316 6.627 10.448 7.452 20.365 5.322 9.91-2.137 17.694-9.422 16.385-16.042-.602-3.025-3.45-3.249-5.433-5.859-2.383-3.127-6.173-4.854-11.56-3.69l-.007-.007Z'
  },
  ff: {
    name: "Final Fantasy",
    sets: FF_SETS,
    hasJumpstart: false,
    themeColor: 'text-black',
    logo: '/images/fin.png',
    iconType: 'svg',
    viewBox: '0 0 350 480',
    icon: 'M175.3 4.4c7.1-4.4 7.2-4.4 8.1-2.2.6 1.3 1 10 1 19.4l.1 17.1 5.5-2.6c4.7-2.1 6.9-2.5 14.5-2.4 5.7 0 12 .8 17.2 2.2 15 3.9 21.3 2.3 30-7.5 1.832-2.068 3.559-3.927 4.727-5.101l.26-.26C257.35 22.384 257.79 22 257.9 22c1.4 0 9.4 14.1 11.3 20 2.5 8.1 2.8 21.6.4 31.3-2.1 9.1-2.1 9.3 1.7 10.8 7.8 3.1 22.7 14.5 22.7 17.4 0 .7-1.7 3.2-3.8 5.6-2.1 2.4-6.5 9.5-9.7 15.6-7.7 14.9-14 21.9-24.5 27.2-4.3 2.2-10.3 4.5-13.3 5.1l-5.4 1.3-.7 7.5c-1 11.6-4.4 22.5-11.2 35.9l-6.2 12.2 6.225 5.81c3.215 2.989 6.186 5.079 6.675 4.59.4-.4 2.2-4.9 3.9-9.8 4.6-13.2 13.9-31.8 20.8-41.4 11.6-16.2 26.6-29.3 42.7-37.4 23.3-11.6 54.6-15 75.8-8.1 11.1 3.6 11.6 15.9 1.3 28-2.7 3.2-3.5 5.1-4.1 10.2l-.7 6.2h2.9c4.9 0 10.5 2.1 13.4 4.9 5.7 5.7 4.6 14.2-3 23.8-3.4 4.2-3.9 5.6-4.4 11.8-.3 3.9-1.5 9.5-2.6 12.5-1.2 3-2.1 6.1-2.1 6.7 0 .7 1.7 2.1 3.9 3.2 13.5 7 14.3 14.7 2.7 26.1-4.2 4.1-5.5 6.2-6.4 10.2-1.8 7.7-7 19.2-12.2 27.1-13.4 20.2-37.6 34.7-65.2 39l-7.9 1.2-2.7 8.1c-1.6 4.4-4.5 10.5-6.6 13.6-4.7 7.1-14.7 16.6-21.9 20.7-3.1 1.8-5.8 4-6.1 4.9-.3.9-1.7 8.7-3.1 17.2l-.142.862c-1.345 8.166-2.568 15.579-2.858 16.738-.3 1.4 3.3 7.9 11.6 20.9 6.7 10.4 12.3 19.5 12.6 20.2.1.275-.719.494-2.992.667l-.574.04c-6.927.46-25.26.58-66.271.592h-3.624L194.5 461h-77.8l.6-6.6c1.6-17.1 8.8-34.3 18.5-44.2 13.5-13.7 33.2-18.7 57.1-14.6 5.1.9 9.6 1.3 9.9.9.8-.8 3-12.8 3.1-17.1l.1-3.2-13.2 3.9c-7.3 2.1-13.6 3.9-14 3.9-.3 0-1.8-2-3.2-4.4-1.4-2.4-4.4-5.8-6.5-7.5-4-3.2-4-3.2-17.8-3.5-11.8-.2-14.7-.6-20.4-2.8-13.1-4.9-21.4-11.3-28.1-21.4-2.9-4.4-7.8-9.5-15.5-16-6.2-5.2-11.3-9.9-11.3-10.5 0-.5 2-3.4 4.5-6.5 2.5-3 4.5-5.8 4.5-6.2 0-.4-2.1-2.8-4.6-5.2-4.4-4.3-11.9-14.1-14.3-18.7-.866-1.653-.678-2.253 5.588-5.41l.521-.26a565.487 565.487 0 0 1 5.991-2.93c9.7-4.7 15-8 19.5-12.1 5.2-4.8 10.3-11.1 10.3-12.8 0-.3-3.7-.8-8.2-1.1-9.4-.6-22.6-4.2-34.1-9.3-9.6-4.2-14.1-4.3-26.1-.8-8.1 2.4-9.4 2.5-14.3 1.4-9.8-2.1-18.3-11.3-21.8-23.5-8.6-29.7 1.9-57.3 27.4-72l8.1-4.7V131c0-24 10.8-50.1 26.7-64.4 6.2-5.5 19.9-13.2 28.6-16.1 7.7-2.5 8.7-3.1 9.2-5.6.4-1.5 2.3-5.4 4.4-8.7 5.2-8 10.9-11.5 22.9-14.3 20-4.5 29.8-8.3 44.5-17.5ZM91.5 120.1C81.2 123.9 75 138 75 157.6c0 14.2 3.7 25 9.9 29.1 6.1 4.1 12.6 2.1 16.3-5 1.7-3.2 2.3-6.4 2.6-14.1.8-17.8-4-30.5-12.5-33.1-3-.8-2.9-2 .3-5 3.3-3.1 8.5-3.3 13.4-.6 10.6 5.6 14.2 32.8 7.1 53.4-1.1 3.2-1.6 5.5-1.1 5.2 1.7-1.1 3.6-5.7 6-14.5 4.4-16.2 2.8-37.3-3.6-45.8-4.6-6-15.3-9.5-21.9-7.1Z'
  },
  ecl: {
    name: "Lorwyn Eclipsed",
    sets: ECL_SETS,
    hasJumpstart: false,
    themeColor: 'text-black',
    logo: null,
    iconType: 'svg',
    viewBox: '0 0 512 512',
    icon: 'M206 42.7c0 2.8 14.7 19.2 23 25.8 8.1 6.4 20.2 22.8 24 32.5 3.8 9.5 3.7 15-.4 27.7l-3.6 11.1 4.4 8.7c9.5 18.4 13.1 34.9 12.3 56-1.1 30-11.6 53.7-33.1 75-15.2 15.2-31.9 24.5-52.6 29.6-7.8 1.9-12.3 2.3-25.5 2.3-18 .1-25.4-1.2-39-6.7-8.9-3.6-26.1-13.2-31.4-17.5l-3.4-2.7 1.5 3c5.2 10 22.9 28.9 37.1 39.6 15.9 12 34.8 21.1 54 25.9 11.3 2.8 29.4 5.6 30.4 4.7.2-.3.9-3.6 1.3-7.4 1.9-14.5 9.4-28.7 22-41.2 8.3-8.2 15.9-12.7 32.3-19.1 25.3-9.9 34.7-15.8 51.3-32.4 20.5-20.5 28.3-38.1 27.1-61.6-.7-12.5-3.9-24.5-10.1-37.5-5.4-11.2-11.7-20.2-23.4-33-10.3-11.3-20.5-26.5-22.8-34-1-3.1-1.9-10.8-2.3-20.4l-.6-15.4-7.2-2.8c-9.8-4-23.7-7.5-36.4-9.4-11.1-1.6-28.9-2.1-28.9-.8z M180.6 45.6c-28.4 5.9-53.1 18.8-74.3 38.9-10.2 9.6-21 22.1-23.8 27.5-1.4 2.6-.7 2.4 8.2-3.2 19.8-12.4 34.7-17.9 53.6-19.7 31.6-3 64 8.3 87.6 30.7l7.3 6.9 1.1-2.6c.6-1.4 1.2-5.8 1.2-9.7 0-6.1-.5-7.9-3.7-14.5-2.1-4-6.1-10.4-9-14-2.9-3.6-9-11.2-13.5-16.7-4.5-5.6-10.4-13.8-13-18.2-5.6-9.3-4.4-9-21.7-5.4zM286.4 63.5c-.3 2-.2 8.5.4 14.4.8 8.8 1.5 11.8 4 16.7 5.2 10 8.5 14.1 18.9 23.3 18.4 16.3 28.8 30.6 36.2 49.6 5.4 13.6 7 20.8 7.8 33.5 1.9 34.6-15 64.7-48.9 86.7-10.1 6.6-21.1 11.1-38.3 15.7-18 4.9-26.8 9-35 16.7-10.6 9.9-16.7 21-19.1 34.2l-.6 3.7h8c4.4 0 13.5-.9 20.3-2.1 32.1-5.4 61.3-20.4 84.5-43.4 16.4-16.3 24.6-28.3 33.9-49.2 19.4-43.4 17.4-94.9-5.2-137.3-14.4-26.8-34.8-47.9-61.5-63.4l-4.7-2.7-.7 3.6zM80.5 132.6c-1.1.2-4.5.9-7.5 1.5s-9.7 3.1-14.9 5.6c-7.9 3.8-10.9 5.9-17.7 12.7-6.7 6.8-9 9.9-12.8 17.7C14.5 197 19.3 226.8 40 248c17.4 17.7 42.8 24.5 67.3 17.9 5.7-1.5 8.5-3 18.1-9.9 16.9-12 25.3-30.7 21.7-48.2-2.8-13.5-12.1-25.1-24.8-31.1-6-2.8-8.1-3.2-17.1-3.5-8.8-.4-11.2-.1-16.5 1.8-12.6 4.6-21.3 12.4-27.4 24.7-2.6 5.4-2.8 6.7-2.8 17.6 0 9.9-.2 11.7-1.5 11.5-2.5-.5-4.2-12.9-3.1-22.4 2.9-23.8 18.7-41.1 42.1-46 11.4-2.4 23.6-.3 35.3 5.8 7.3 3.9 17.4 14.6 21.7 22.9l3.2 6.4-.7-5.5c-1.6-13.8-8.3-26.8-19.5-38-8.2-8.1-19.4-14.7-30-17.5-5.6-1.6-21.9-2.8-25.5-1.9z'
  }
};

export const MANA_SYMBOLS: Record<string, string> = {
  // Basic
  'W': 'https://svgs.scryfall.io/card-symbols/W.svg',
  'U': 'https://svgs.scryfall.io/card-symbols/U.svg',
  'B': 'https://svgs.scryfall.io/card-symbols/B.svg',
  'R': 'https://svgs.scryfall.io/card-symbols/R.svg',
  'G': 'https://svgs.scryfall.io/card-symbols/G.svg',
  'C': 'https://svgs.scryfall.io/card-symbols/C.svg',
  'S': 'https://svgs.scryfall.io/card-symbols/S.svg', // Snow
  
  // Generic / Numbers
  'X': 'https://svgs.scryfall.io/card-symbols/X.svg',
  'Y': 'https://svgs.scryfall.io/card-symbols/Y.svg',
  'Z': 'https://svgs.scryfall.io/card-symbols/Z.svg',
  '0': 'https://svgs.scryfall.io/card-symbols/0.svg',
  '½': 'https://svgs.scryfall.io/card-symbols/HALF.svg',
  '1': 'https://svgs.scryfall.io/card-symbols/1.svg',
  '2': 'https://svgs.scryfall.io/card-symbols/2.svg',
  '3': 'https://svgs.scryfall.io/card-symbols/3.svg',
  '4': 'https://svgs.scryfall.io/card-symbols/4.svg',
  '5': 'https://svgs.scryfall.io/card-symbols/5.svg',
  '6': 'https://svgs.scryfall.io/card-symbols/6.svg',
  '7': 'https://svgs.scryfall.io/card-symbols/7.svg',
  '8': 'https://svgs.scryfall.io/card-symbols/8.svg',
  '9': 'https://svgs.scryfall.io/card-symbols/9.svg',
  '10': 'https://svgs.scryfall.io/card-symbols/10.svg',
  '11': 'https://svgs.scryfall.io/card-symbols/11.svg',
  '12': 'https://svgs.scryfall.io/card-symbols/12.svg',
  '13': 'https://svgs.scryfall.io/card-symbols/13.svg',
  '14': 'https://svgs.scryfall.io/card-symbols/14.svg',
  '15': 'https://svgs.scryfall.io/card-symbols/15.svg',
  '16': 'https://svgs.scryfall.io/card-symbols/16.svg',
  '17': 'https://svgs.scryfall.io/card-symbols/17.svg',
  '18': 'https://svgs.scryfall.io/card-symbols/18.svg',
  '19': 'https://svgs.scryfall.io/card-symbols/19.svg',
  '20': 'https://svgs.scryfall.io/card-symbols/20.svg',
  '100': 'https://svgs.scryfall.io/card-symbols/100.svg',
  '1000000': 'https://svgs.scryfall.io/card-symbols/1000000.svg',
  '∞': 'https://svgs.scryfall.io/card-symbols/INFINITY.svg',

  // Tap/Untap/Special
  'T': 'https://svgs.scryfall.io/card-symbols/T.svg', 
  'Q': 'https://svgs.scryfall.io/card-symbols/Q.svg',
  'E': 'https://svgs.scryfall.io/card-symbols/E.svg',
  'P': 'https://svgs.scryfall.io/card-symbols/P.svg',
  'PW': 'https://svgs.scryfall.io/card-symbols/PW.svg',
  'CHAOS': 'https://svgs.scryfall.io/card-symbols/CHAOS.svg',
  'A': 'https://svgs.scryfall.io/card-symbols/A.svg',
  'TK': 'https://svgs.scryfall.io/card-symbols/TK.svg',

  // Hybrid
  'W/U': 'https://svgs.scryfall.io/card-symbols/WU.svg',
  'W/B': 'https://svgs.scryfall.io/card-symbols/WB.svg',
  'B/R': 'https://svgs.scryfall.io/card-symbols/BR.svg',
  'B/G': 'https://svgs.scryfall.io/card-symbols/BG.svg',
  'U/B': 'https://svgs.scryfall.io/card-symbols/UB.svg',
  'U/R': 'https://svgs.scryfall.io/card-symbols/UR.svg',
  'R/G': 'https://svgs.scryfall.io/card-symbols/RG.svg',
  'R/W': 'https://svgs.scryfall.io/card-symbols/RW.svg',
  'G/W': 'https://svgs.scryfall.io/card-symbols/GW.svg',
  'G/U': 'https://svgs.scryfall.io/card-symbols/GU.svg',

  // Phyrexian Hybrid
  'B/G/P': 'https://svgs.scryfall.io/card-symbols/BGP.svg',
  'B/R/P': 'https://svgs.scryfall.io/card-symbols/BRP.svg',
  'G/U/P': 'https://svgs.scryfall.io/card-symbols/GUP.svg',
  'G/W/P': 'https://svgs.scryfall.io/card-symbols/GWP.svg',
  'R/G/P': 'https://svgs.scryfall.io/card-symbols/RGP.svg',
  'R/W/P': 'https://svgs.scryfall.io/card-symbols/RWP.svg',
  'U/B/P': 'https://svgs.scryfall.io/card-symbols/UBP.svg',
  'U/R/P': 'https://svgs.scryfall.io/card-symbols/URP.svg',
  'W/B/P': 'https://svgs.scryfall.io/card-symbols/WBP.svg',
  'W/U/P': 'https://svgs.scryfall.io/card-symbols/WUP.svg',

  // Colorless Hybrid
  'C/W': 'https://svgs.scryfall.io/card-symbols/CW.svg',
  'C/U': 'https://svgs.scryfall.io/card-symbols/CU.svg',
  'C/B': 'https://svgs.scryfall.io/card-symbols/CB.svg',
  'C/R': 'https://svgs.scryfall.io/card-symbols/CR.svg',
  'C/G': 'https://svgs.scryfall.io/card-symbols/CG.svg',

  // 2/Color Hybrid
  '2/W': 'https://svgs.scryfall.io/card-symbols/2W.svg',
  '2/U': 'https://svgs.scryfall.io/card-symbols/2U.svg',
  '2/B': 'https://svgs.scryfall.io/card-symbols/2B.svg',
  '2/R': 'https://svgs.scryfall.io/card-symbols/2R.svg',
  '2/G': 'https://svgs.scryfall.io/card-symbols/2G.svg',

  // Phyrexian
  'H': 'https://svgs.scryfall.io/card-symbols/H.svg',
  'W/P': 'https://svgs.scryfall.io/card-symbols/WP.svg',
  'U/P': 'https://svgs.scryfall.io/card-symbols/UP.svg',
  'B/P': 'https://svgs.scryfall.io/card-symbols/BP.svg',
  'R/P': 'https://svgs.scryfall.io/card-symbols/RP.svg',
  'G/P': 'https://svgs.scryfall.io/card-symbols/GP.svg',
  'C/P': 'https://svgs.scryfall.io/card-symbols/CP.svg',

  // Half
  'HW': 'https://svgs.scryfall.io/card-symbols/HW.svg',
  'HR': 'https://svgs.scryfall.io/card-symbols/HR.svg',
  
  // Misc
  'L': 'https://svgs.scryfall.io/card-symbols/L.svg',
  'D': 'https://svgs.scryfall.io/card-symbols/D.svg',
};

// Hardcoded Beginner Box Decks from the user's HTML
export const BEGINNER_DECKS: Deck[] = [
    { 
        title: "Aang Tutorial", source: 'Beginner Box', themeCard: "Aang, Air Nomad",
        cards: [
            { name: "Aang, Air Nomad", qty: 1 }, { name: "Sokka, Wolf Cove's Protector", qty: 1 }, { name: "Momo, Rambunctious Rascal", qty: 1 }, { name: "Katara, Heroic Healer", qty: 1 }, { name: "Appa, Aang's Companion", qty: 1 }, { name: "Wolf Cove Villager", qty: 1 }, { name: "Tundra Wall", qty: 1 }, { name: "Aang's Defense", qty: 1 }, { name: "Sledding Otter-Penguin", qty: 1 }, { name: "Path to Redemption", qty: 1 }, { name: "Razor Rings", qty: 1 }, { name: "Aardvark Sloth", qty: 1 }, { name: "Plains", qty: 8 }
        ],
        strategy: "Flying/Evasion, Ally Tribal", strengths: "Ground-based decks", weaknesses: "Must-answer threats", pairings: ["Allies", "Spells"], summary: "Led by Aang, Air Nomad, this deck focuses on Flying/Evasion, Ally Tribal. It shines against ground-based decks, but struggles against must-answer threats."
    },
    {
        title: "Zuko Tutorial", source: 'Beginner Box', themeCard: "Zuko, Avatar Hunter",
        cards: [
            { name: "Dragon Moose", qty: 1 }, { name: "Explosive Shot", qty: 1 }, { name: "Run Amok", qty: 1 }, { name: "Fire Nation's Conquest", qty: 1 }, { name: "Komodo Rhino", qty: 1 }, { name: "Zuko, Avatar Hunter", qty: 1 }, { name: "Zhao, the Seething Flame", qty: 1 }, { name: "Iroh, Firebending Instructor", qty: 1 }, { name: "Zuko's Offense", qty: 1 }, { name: "Fire Nation Soldier", qty: 1 }, { name: "Capital Guard", qty: 1 }, { name: "Warship Scout", qty: 1 }, { name: "Mountain", qty: 8 }
        ],
        strategy: "Midrange", strengths: "Balanced strategies", weaknesses: "Must-answer threats", pairings: ["Counters", "Firebending"], summary: "Led by Zuko, Avatar Hunter, this deck focuses on Midrange. It shines against balanced strategies, but struggles against must-answer threats."
    },
    {
        title: "Allies", source: 'Beginner Box', themeCard: "Aang, the Last Airbender",
        cards: [{ name: "Kyoshi Warrior Guard", qty: 1 }, { name: "Jeong Jeong's Deserters", qty: 1 }, { name: "Glider Kids", qty: 1 }, { name: "Avatar Enthusiasts", qty: 1 }, { name: "Aang, the Last Airbender", qty: 1 }, { name: "Suki, Kyoshi Warrior", qty: 1 }, { name: "Rabaroo Troop", qty: 1 }, { name: "Master Piandao", qty: 1 }, { name: "Allied Teamwork", qty: 1 }, { name: "Path to Redemption", qty: 1 }, { name: "Mechanical Glider", qty: 1 }, { name: "Airbending Lesson", qty: 1 }, { name: "Thriving Heath", qty: 1 }, { name: "Plains", qty: 7 }],
        strategy: "Flying/Evasion, Ally Tribal", strengths: "Ground-based decks, Creature-heavy strategies", weaknesses: "Control decks", pairings: ["Aang Tutorial", "Spells"], summary: "Led by Aang, the Last Airbender, this deck focuses on Flying/Evasion, Ally Tribal. It shines against ground-based decks, creature-heavy strategies, but struggles against control decks."
    }
];

// Appa land mapping - TLA 287-291
export const APPA_LAND_MAP: Record<string, string> = {
    'Plains Appa': '287',
    'Island Appa': '288',
    'Swamp Appa': '289',
    'Mountain Appa': '290',
    'Forest Appa': '291'
};

export const DECK_SUMMARIES: Record<string, any> = {
    "Aang (0001)": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Hunting (0022) - Variation 2", "Lessons (0013) - Variation 2", "Wise (0018) - Variation 1"], summary: "Commanded by Momo, Rambunctious Rascal, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Adaptive (0010)": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Ground-stalled decks, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Soaring (0015) - Variation 1", "Aang (0001)", "Adept (0011) - Variation 1"], summary: "Commanded by Katara, Bending Prodigy, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against ground-stalled decks, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Adept (0011) - Variation 1": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Spot Removal heavy decks (overwhelms 1-for-1), Decks with few blockers", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Adept (0011) - Variation 2", "Soaring (0015) - Variation 2", "Aang (0001)"], summary: "Commanded by Professor Zei, Anthropologist, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against spot removal heavy decks (overwhelms 1-for-1), decks with few blockers, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Adept (0011) - Variation 2": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Ground-stalled decks, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Adept (0011) - Variation 1", "Soaring (0015) - Variation 2", "Aang (0001)"], summary: "Commanded by Professor Zei, Anthropologist, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against ground-stalled decks, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Airbending (0002)": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Bumi (0038)", "Firebending (0029) - Variation 2", "Hei Bai (0006) - Variation 1"], summary: "Commanded by Monk Gyatso, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Alliance (0003) - Variation 1": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Control (gets under them), Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Alliance (0003) - Variation 2", "Earth Kingdom (0040) - Variation 1", "Rebelling (0033) - Variation 2"], summary: "Commanded by The Duke, Rebel Sentry, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against control (gets under them), spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Alliance (0003) - Variation 2": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Control (gets under them), Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Alliance (0003) - Variation 1", "Earth Kingdom (0040) - Variation 1", "Rebelling (0033) - Variation 2"], summary: "Commanded by The Duke, Rebel Sentry, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against control (gets under them), spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "At the Zoo (0037)": { strategy: "Go-wide Tokens, +1/+1 Counters", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "Azula (0019)", "Bad Advice (0020)"], summary: "Commanded by Turtle-Duck, this deck employs Go-wide Tokens, +1/+1 Counters to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Azula (0019)": { strategy: "Go-wide Tokens", strengths: "Spot Removal heavy decks (overwhelms 1-for-1), Decks with few blockers", weaknesses: "Flyers (often can't block air), Trample (damage pushes through)", pairings: ["Airbending (0002)", "At the Zoo (0037)", "Bad Advice (0020)"], summary: "Commanded by Azula, Ruthless Firebender, this deck employs Go-wide Tokens to dominate the field. It excels against spot removal heavy decks (overwhelms 1-for-1), decks with few blockers, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), trample (damage pushes through)." },
    "Bad Advice (0020)": { strategy: "Go-wide Tokens, +1/+1 Counters", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "At the Zoo (0037)", "Azula (0019)"], summary: "Commanded by Long Feng, Grand Secretariat, this deck employs Go-wide Tokens, +1/+1 Counters to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Bounty Hunter (0021) - Variation 1": { strategy: "Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Aang (0001)", "Bounty Hunter (0021) - Variation 2", "Fire Nation (0028)"], summary: "Commanded by June, Bounty Hunter, this deck employs Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Bounty Hunter (0021) - Variation 2": { strategy: "Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Aang (0001)", "Bounty Hunter (0021) - Variation 1", "Fire Nation (0028)"], summary: "Commanded by June, Bounty Hunter, this deck employs Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Bumi (0038)": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "Firebending (0029) - Variation 2", "Hei Bai (0006) - Variation 1"], summary: "Commanded by Aang, A Lot to Learn, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Cabbages (0039)": { strategy: "Go-wide Tokens, +1/+1 Counters", strengths: "Spot Removal heavy decks (overwhelms 1-for-1), Decks with few blockers", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Adept (0011) - Variation 1", "Adept (0011) - Variation 2", "Librarian (0014)"], summary: "Commanded by The Cabbage Merchant, this deck employs Go-wide Tokens, +1/+1 Counters to dominate the field. It excels against spot removal heavy decks (overwhelms 1-for-1), decks with few blockers, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Earth Kingdom (0040) - Variation 1": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Spot Removal heavy decks (overwhelms 1-for-1), Decks with few blockers", weaknesses: "Flyers (often can't block air), Trample (damage pushes through)", pairings: ["Alliance (0003) - Variation 1", "Alliance (0003) - Variation 2", "Rebelling (0033) - Variation 2"], summary: "Commanded by Haru, Hidden Talent, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against spot removal heavy decks (overwhelms 1-for-1), decks with few blockers, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), trample (damage pushes through)." },
    "Earth Kingdom (0040) - Variation 2": { strategy: "Ally Tribal, +1/+1 Counters", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "Alliance (0003) - Variation 1", "Alliance (0003) - Variation 2"], summary: "Commanded by Haru, Hidden Talent, this deck employs Ally Tribal, +1/+1 Counters to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Earth Rumble (0041) - Variation 1": { strategy: "Warrior Tribal, +1/+1 Counters", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Warriors (0009)", "Earth Kingdom (0040) - Variation 2", "At the Zoo (0037)"], summary: "Commanded by Uncle Iroh, this deck employs Warrior Tribal, +1/+1 Counters to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Earth Rumble (0041) - Variation 2": { strategy: "Go-wide Tokens, +1/+1 Counters", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Alliance (0003) - Variation 1", "Alliance (0003) - Variation 2", "Earth Kingdom (0040) - Variation 1"], summary: "Commanded by Uncle Iroh, this deck employs Go-wide Tokens, +1/+1 Counters to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Earthbending (0042) - Variation 1": { strategy: "Ally Tribal, +1/+1 Counters", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Earthbending (0042) - Variation 2", "Aang (0001)", "Adept (0011) - Variation 1"], summary: "Commanded by Toph, the Blind Bandit, this deck employs Ally Tribal, +1/+1 Counters to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Earthbending (0042) - Variation 2": { strategy: "Ally Tribal, +1/+1 Counters", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Earthbending (0042) - Variation 1", "Aang (0001)", "Adept (0011) - Variation 1"], summary: "Commanded by Toph, the Blind Bandit, this deck employs Ally Tribal, +1/+1 Counters to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Fire Nation (0028)": { strategy: "Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Aang (0001)", "Bounty Hunter (0021) - Variation 1", "Bounty Hunter (0021) - Variation 2"], summary: "Commanded by Mai, Jaded Edge, this deck employs Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Firebending (0029) - Variation 1": { strategy: "Go-wide Tokens", strengths: "Spot Removal heavy decks (overwhelms 1-for-1), Decks with few blockers", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Airbending (0002)", "At the Zoo (0037)", "Azula (0019)"], summary: "Commanded by Jeong Jeong, the Deserter, this deck employs Go-wide Tokens to dominate the field. It excels against spot removal heavy decks (overwhelms 1-for-1), decks with few blockers, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Firebending (0029) - Variation 2": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "Bumi (0038)", "Hei Bai (0006) - Variation 1"], summary: "Commanded by Moku, Meandering Drummer, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Freedom Fighters (0004)": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Gliding (0005) - Variation 1", "Gliding (0005) - Variation 2", "Swordmaster (0008)"], summary: "Commanded by The Duke, Rebel Sentry, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Gliding (0005) - Variation 1": { strategy: "Ally Tribal, Flying/Evasion", strengths: "Ground-stalled decks, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Freedom Fighters (0004)", "Gliding (0005) - Variation 2", "Swordmaster (0008)"], summary: "Commanded by Momo, Friendly Flier, this deck employs Ally Tribal, Flying/Evasion to dominate the field. It excels against ground-stalled decks, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Gliding (0005) - Variation 2": { strategy: "Ally Tribal, Flying/Evasion", strengths: "Ground-stalled decks, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Freedom Fighters (0004)", "Gliding (0005) - Variation 1", "Swordmaster (0008)"], summary: "Commanded by Momo, Friendly Flier, this deck employs Ally Tribal, Flying/Evasion to dominate the field. It excels against ground-stalled decks, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Hei Bai (0006) - Variation 1": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Control (gets under them), Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Flyers (often can't block air), Trample (damage pushes through)", pairings: ["Airbending (0002)", "Bumi (0038)", "Firebending (0029) - Variation 2"], summary: "Commanded by Aang, A Lot to Learn, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against control (gets under them), spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), trample (damage pushes through)." },
    "Hei Bai (0006) - Variation 2": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "Bumi (0038)", "Firebending (0029) - Variation 2"], summary: "Commanded by Aang, A Lot to Learn, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Hunting (0022) - Variation 1": { strategy: "Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Aang (0001)", "Bounty Hunter (0021) - Variation 1", "Bounty Hunter (0021) - Variation 2"], summary: "Commanded by June, Bounty Hunter, this deck employs Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Hunting (0022) - Variation 2": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Aang (0001)", "Lessons (0013) - Variation 2", "Wise (0018) - Variation 1"], summary: "Commanded by June, Bounty Hunter, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Insurgent (0007) - Variation 1": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "Bumi (0038)", "Firebending (0029) - Variation 2"], summary: "Commanded by Momo, Rambunctious Rascal, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Insurgent (0007) - Variation 2": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "Bumi (0038)", "Firebending (0029) - Variation 2"], summary: "Commanded by Momo, Rambunctious Rascal, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Iroh (0030)": { strategy: "Ally Tribal, +1/+1 Counters", strengths: "Small Aggro (outscales them)", weaknesses: "Bomb-heavy decks (cannot remove threats), Flying/Evasive decks", pairings: ["Airbending (0002)", "Bumi (0038)", "Earth Kingdom (0040) - Variation 2"], summary: "Commanded by Zuko, Seeking Honor, this deck employs Ally Tribal, +1/+1 Counters to dominate the field. It excels against small aggro (outscales them), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flying/evasive decks." },
    "Katara (0012)": { strategy: "Ally Tribal, Graveyard Recursion", strengths: "Control (gets under them), Slow setup decks", weaknesses: "Bomb-heavy decks (cannot remove threats), Flying/Evasive decks", pairings: ["Lessons (0013) - Variation 1", "Aang (0001)", "Adaptive (0010)"], summary: "Commanded by Gran-Gran, this deck employs Ally Tribal, Graveyard Recursion to dominate the field. It excels against control (gets under them), slow setup decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flying/evasive decks." },
    "Kyoshi (0043)": { strategy: "Go-wide Tokens, +1/+1 Counters", strengths: "Spot Removal heavy decks (overwhelms 1-for-1), Decks with few blockers", weaknesses: "Flyers (often can't block air), Fast Aggro", pairings: ["Alliance (0003) - Variation 1", "Alliance (0003) - Variation 2", "Earth Kingdom (0040) - Variation 1"], summary: "Commanded by Suki, Kyoshi Warrior, this deck employs Go-wide Tokens, +1/+1 Counters to dominate the field. It excels against spot removal heavy decks (overwhelms 1-for-1), decks with few blockers, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), fast aggro." },
    "Learning (0044) - Variation 1": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "Bumi (0038)", "Earth Kingdom (0040) - Variation 2"], summary: "Commanded by Aang, A Lot to Learn, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Learning (0044) - Variation 2": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Adept (0011) - Variation 1", "Adept (0011) - Variation 2", "Airbending (0002)"], summary: "Commanded by Aang, A Lot to Learn, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Lessons (0013) - Variation 1": { strategy: "Ally Tribal", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Aang (0001)", "Earthbending (0042) - Variation 1", "Earthbending (0042) - Variation 2"], summary: "Commanded by Gran-Gran, this deck employs Ally Tribal to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Lessons (0013) - Variation 2": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Aang (0001)", "Hunting (0022) - Variation 2", "Wise (0018) - Variation 1"], summary: "Commanded by Gran-Gran, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Librarian (0014)": { strategy: "Spirit Tribal, Go-wide Tokens", strengths: "Spot Removal heavy decks (overwhelms 1-for-1), Decks with few blockers", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Spirit (0016)", "Adept (0011) - Variation 1", "Adept (0011) - Variation 2"], summary: "Commanded by Professor Zei, Anthropologist, this deck employs Spirit Tribal, Go-wide Tokens to dominate the field. It excels against spot removal heavy decks (overwhelms 1-for-1), decks with few blockers, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Musicians (0031)": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "Bumi (0038)", "Firebending (0029) - Variation 2"], summary: "Commanded by Moku, Meandering Drummer, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Nightmares (0023)": { strategy: "Go-wide Tokens, Graveyard Recursion", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "At the Zoo (0037)", "Azula (0019)"], summary: "Commanded by Azula, On the Hunt, this deck employs Go-wide Tokens, Graveyard Recursion to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Ozai (0024)": { strategy: "Soldier Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Relentless (0026) - Variation 2", "Aang (0001)", "Bounty Hunter (0021) - Variation 1"], summary: "Commanded by Fire Lord Ozai, this deck employs Soldier Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Powerful (0032) - Variation 1": { strategy: "Go-wide Tokens, Equipment Voltron", strengths: "Spot Removal heavy decks (overwhelms 1-for-1), Decks with few blockers", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Alliance (0003) - Variation 1", "Alliance (0003) - Variation 2", "Earth Kingdom (0040) - Variation 1"], summary: "Commanded by Uncle Iroh, this deck employs Go-wide Tokens, Equipment Voltron to dominate the field. It excels against spot removal heavy decks (overwhelms 1-for-1), decks with few blockers, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Powerful (0032) - Variation 2": { strategy: "Go-wide Tokens", strengths: "Spot Removal heavy decks (overwhelms 1-for-1), Decks with few blockers", weaknesses: "Flyers (often can't block air), Flying/Evasive decks", pairings: ["Airbending (0002)", "At the Zoo (0037)", "Azula (0019)"], summary: "Commanded by Uncle Iroh, this deck employs Go-wide Tokens to dominate the field. It excels against spot removal heavy decks (overwhelms 1-for-1), decks with few blockers, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), flying/evasive decks." },
    "Rebelling (0033) - Variation 1": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "Bumi (0038)", "Firebending (0029) - Variation 2"], summary: "Commanded by Zuko, Seeking Honor, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Rebelling (0033) - Variation 2": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Spot Removal heavy decks (overwhelms 1-for-1), Decks with few blockers", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Alliance (0003) - Variation 1", "Alliance (0003) - Variation 2", "Earth Kingdom (0040) - Variation 1"], summary: "Commanded by Zuko, Seeking Honor, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against spot removal heavy decks (overwhelms 1-for-1), decks with few blockers, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Reinforced (0025) - Variation 1": { strategy: "Go-wide Tokens, +1/+1 Counters", strengths: "Strategy-dependent combos, Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "At the Zoo (0037)", "Azula (0019)"], summary: "Commanded by Long Feng, Grand Secretariat, this deck employs Go-wide Tokens, +1/+1 Counters to dominate the field. It excels against strategy-dependent combos, spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Reinforced (0025) - Variation 2": { strategy: "+1/+1 Counters", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Earthbending (0042) - Variation 1", "Earthbending (0042) - Variation 2", "At the Zoo (0037)"], summary: "Commanded by Long Feng, Grand Secretariat, this deck employs +1/+1 Counters to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Relentless (0026) - Variation 1": { strategy: "Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Adept (0011) - Variation 1", "Adept (0011) - Variation 2", "Cabbages (0039)"], summary: "Commanded by Azula, On the Hunt, this deck employs Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Relentless (0026) - Variation 2": { strategy: "Soldier Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Ozai (0024)", "Adept (0011) - Variation 1", "Adept (0011) - Variation 2"], summary: "Commanded by Azula, On the Hunt, this deck employs Soldier Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Roku (0034)": { strategy: "Go-wide Tokens, +1/+1 Counters", strengths: "Control (gets under them), Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Adept (0011) - Variation 1", "Adept (0011) - Variation 2", "Cabbages (0039)"], summary: "Commanded by Jeong Jeong, the Deserter, this deck employs Go-wide Tokens, +1/+1 Counters to dominate the field. It excels against control (gets under them), spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Shrines (0046)": { strategy: "Go-wide Tokens, +1/+1 Counters", strengths: "Spot Removal heavy decks (overwhelms 1-for-1), Decks with few blockers", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Adept (0011) - Variation 1", "Adept (0011) - Variation 2", "Cabbages (0039)"], summary: "Commanded by Hei Bai, Forest Guardian, this deck employs Go-wide Tokens, +1/+1 Counters to dominate the field. It excels against spot removal heavy decks (overwhelms 1-for-1), decks with few blockers, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Siege Engines (0027)": { strategy: "Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Aang (0001)", "Bounty Hunter (0021) - Variation 1", "Bounty Hunter (0021) - Variation 2"], summary: "Commanded by Callous Inspector, this deck employs Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Soaring (0015) - Variation 1": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Control (gets under them), Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Adaptive (0010)", "Aang (0001)", "Adept (0011) - Variation 1"], summary: "Commanded by Sokka, Lateral Strategist, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against control (gets under them), spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Soaring (0015) - Variation 2": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Control (gets under them), Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Adept (0011) - Variation 1", "Adept (0011) - Variation 2", "Aang (0001)"], summary: "Commanded by Sokka, Lateral Strategist, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against control (gets under them), spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Sparky Sparky (0035) - Variation 1": { strategy: "Control", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Sparky Sparky (0035) - Variation 2", "Airbending (0002)", "At the Zoo (0037)"], summary: "Commanded by Zuko, Exiled Prince, this deck employs Control to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Sparky Sparky (0035) - Variation 2": { strategy: "Control", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Sparky Sparky (0035) - Variation 1", "Aang (0001)", "Bounty Hunter (0021) - Variation 1"], summary: "Commanded by Zuko, Exiled Prince, this deck employs Control to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Spirit (0016)": { strategy: "Spirit Tribal, Go-wide Tokens", strengths: "Control (gets under them), Spot Removal heavy decks (overwhelms 1-for-1)", weaknesses: "Bomb-heavy decks (cannot remove threats), Flyers (often can't block air)", pairings: ["Librarian (0014)", "Adept (0011) - Variation 1", "Adept (0011) - Variation 2"], summary: "Commanded by Flying Dolphin-Fish, this deck employs Spirit Tribal, Go-wide Tokens to dominate the field. It excels against control (gets under them), spot removal heavy decks (overwhelms 1-for-1), leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats), flyers (often can't block air)." },
    "Swordmaster (0008)": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Freedom Fighters (0004)", "Gliding (0005) - Variation 1", "Gliding (0005) - Variation 2"], summary: "Commanded by Sokka, Swordmaster, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Toph (0045)": { strategy: "Ally Tribal, +1/+1 Counters", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Airbending (0002)", "Bumi (0038)", "Earth Kingdom (0040) - Variation 2"], summary: "Commanded by Toph, Earthbending Master, this deck employs Ally Tribal, +1/+1 Counters to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Underwater (0017)": { strategy: "Midrange", strengths: "Balanced decks", weaknesses: "Bomb-heavy decks (cannot remove threats)", pairings: ["Zuko (0036)", "Adept (0011) - Variation 1", "Adept (0011) - Variation 2"], summary: "Commanded by Tui and La, Moon and Ocean, this deck employs Midrange to dominate the field. It excels against balanced decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing bomb-heavy decks (cannot remove threats)." },
    "Warriors (0009)": { strategy: "Warrior Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Earth Rumble (0041) - Variation 1", "Freedom Fighters (0004)", "Swordmaster (0008)"], summary: "Commanded by Sokka, Lateral Strategist, this deck employs Warrior Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    "Wise (0018) - Variation 1": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Aang (0001)", "Hunting (0022) - Variation 2", "Lessons (0013) - Variation 2"], summary: "Commanded by Gran-Gran, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Wise (0018) - Variation 2": { strategy: "Ally Tribal, Go-wide Tokens", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Flyers (often can't block air), Go-wide strategies (too many threats)", pairings: ["Aang (0001)", "Hunting (0022) - Variation 2", "Lessons (0013) - Variation 2"], summary: "Commanded by Sokka, Lateral Strategist, this deck employs Ally Tribal, Go-wide Tokens to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing flyers (often can't block air), go-wide strategies (too many threats)." },
    "Zuko (0036)": { strategy: "Midrange", strengths: "Strategy-dependent combos, Midrange/Value decks", weaknesses: "Haste/Flash creatures, Go-wide strategies (too many threats)", pairings: ["Aang (0001)", "Bounty Hunter (0021) - Variation 1", "Bounty Hunter (0021) - Variation 2"], summary: "Commanded by Zuko, Firebending Master, this deck employs Midrange to dominate the field. It excels against strategy-dependent combos, midrange/value decks, leveraging its mechanics to press the advantage. However, it must be wary of opponents utilizing haste/flash creatures, go-wide strategies (too many threats)." },
    
    // Beginner Box Decks
    "Aang Tutorial (01)": { strategy: "Flying/Evasion, Ally Tribal", strengths: "Ground-based decks", weaknesses: "Must-answer threats", pairings: ["Allies (03)", "Spells (05)"], summary: "Led by Aang, Air Nomad, this deck focuses on Flying/Evasion, Ally Tribal. It shines against ground-based decks, but struggles against must-answer threats." },
    "Zuko Tutorial (02)": { strategy: "Midrange", strengths: "Balanced strategies", weaknesses: "Must-answer threats", pairings: ["Counters (07)", "Firebending (08)"], summary: "Led by Zuko, Avatar Hunter, this deck focuses on Midrange. It shines against balanced strategies, but struggles against must-answer threats." },
    "Allies (03)": { strategy: "Flying/Evasion, Ally Tribal", strengths: "Ground-based decks, Creature-heavy strategies", weaknesses: "Control decks", pairings: ["Aang Tutorial (01)", "Spells (05)"], summary: "Led by Aang, the Last Airbender, this deck focuses on Flying/Evasion, Ally Tribal. It shines against ground-based decks, creature-heavy strategies, but struggles against control decks." },
    "Waterbending (04)": { strategy: "Warrior Tribal, Flying/Evasion", strengths: "Ground-based decks", weaknesses: "Must-answer threats", pairings: ["Aang Tutorial (01)", "Big Creatures (09)"], summary: "Led by Katara, Bending Prodigy, this deck focuses on Warrior Tribal, Flying/Evasion. It shines against ground-based decks, but struggles against must-answer threats." },
    "Spells (05)": { strategy: "Graveyard Recursion, Ally Tribal", strengths: "Ground-based decks, Single-target removal", weaknesses: "Must-answer threats", pairings: ["Aang Tutorial (01)", "Allies (03)"], summary: "Led by Master Pakku, this deck focuses on Graveyard Recursion, Ally Tribal. It shines against ground-based decks, single-target removal, but struggles against must-answer threats." },
    "Attacking (06)": { strategy: "Graveyard Recursion, +1/+1 Counters", strengths: "Slow setup decks, Smaller Aggro decks", weaknesses: "Control decks", pairings: ["Counters (07)", "Earthbending (10)"], summary: "Led by Hei Bai, Spirit of Balance, this deck focuses on Graveyard Recursion, +1/+1 Counters. It shines against slow setup decks, smaller aggro decks, but struggles against control decks." },
    "Counters (07)": { strategy: "+1/+1 Counters", strengths: "Slow setup decks, Smaller Aggro decks", weaknesses: "Flying/Evasion", pairings: ["Attacking (06)", "Earthbending (10)"], summary: "Led by Long Feng, Grand Secretariat, this deck focuses on +1/+1 Counters. It shines against slow setup decks, smaller aggro decks, but struggles against flying/evasion." },
    "Firebending (08)": { strategy: "Go-wide Tokens", strengths: "Single-target removal", weaknesses: "Must-answer threats", pairings: ["Counters (07)", "Attacking (06)"], summary: "Led by Zuko, Exiled Prince, this deck focuses on Go-wide Tokens. It shines against single-target removal, but struggles against must-answer threats." },
    "Big Creatures (09)": { strategy: "Flying/Evasion, Graveyard Recursion", strengths: "Ground-based decks, Smaller Aggro decks", weaknesses: "Must-answer threats", pairings: ["Attacking (06)", "Aang Tutorial (01)"], summary: "Led by Flopsie, Bumi's Buddy, this deck focuses on Flying/Evasion, Graveyard Recursion. It shines against ground-based decks, smaller aggro decks, but struggles against must-answer threats." },
    "Earthbending (10)": { strategy: "+1/+1 Counters", strengths: "Creature-heavy strategies, Smaller Aggro decks", weaknesses: "Control decks", pairings: ["Attacking (06)", "Counters (07)"], summary: "Led by Haru, Hidden Talent, this deck focuses on +1/+1 Counters. It shines against creature-heavy strategies, smaller aggro decks, but struggles against control decks." }
};
